exclude: '^docs/|/migrations/'
default_stages: [commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-docstring-first
          - id: detect-private-key

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            args: ['--tab-width', '4', '--single-quote']
            exclude: 'templates/'

    - repo: https://github.com/PyCQA/autoflake
      rev: v2.2.1
      hooks:
          - id: autoflake
            args: [--remove-all-unused-imports, --in-place]

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ['--profile', 'black', --line-length=80]

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            args: [--line-length=80]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: [--config, setup.cfg]

    - repo: https://github.com/Riverside-Healthcare/djLint
      rev: v1.34.0
      hooks:
          - id: djlint-reformat-django
          - id: djlint-django
            args: [--ignore=H006]

    - repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: mypy
            language: system
            types: [python]
